web/config/routes.rb
# encoding: utf-8

Seee::Application.routes.draw do
  resources :forms do
    member do
      get "/copy_to_current" => "forms#copy_to_current"
      get "/preview" => "forms#preview"
    end
  end

  resources :faculties

  match "/tutors" => "tutors#index"
  resources :courses do
    resources :tutors
    get "/emergency_printing" => "courses#emergency_printing"
    post "/emergency_printing" => "courses#emergency_printing"
    get "/tutors/:id/preview" => "tutors#preview", :as => "tutor_preview"
    post "/tutors/:id/result_pdf" => "tutors#result_pdf", :as => "tutor_result_pdf"
    member do
      post "/add_prof" => "courses#add_prof"
      delete "/drop_prof" => "courses#drop_prof"
      get "/preview" => "courses#preview"
      get "/correlate" => "courses#correlate"
    end
  end

  resources :profs

  resources :terms do
    get "/courses" => "courses#index"
  end

  root :to => "courses#index"

  post "/course_profs/:id/print" => "course_profs#print", :as => :print_course_prof

  # comment image source pass throughs
  get "/pics/:id/download" => "pics#download", :as => :download_pic
  get "/cpics/:id/download" => "CPics#download", :as => :download_cpic


  get "/hitme" => "hitmes#overview"
  get "/hitme/assign_work" => "hitmes#assign_work"
  get "/hitme/cookie_test" => "hitmes#cookie_test"
  get "/hitme/active_users" => "hitmes#active_users"
  post "/hitme/preview_text" => "hitmes#preview_text"
  post "/hitme/save_comment" => "hitmes#save_comment"
  post "/hitme/save_combination" => "hitmes#save_combination"
  post "/hitme/save_final_check" => "hitmes#save_final_check"


  match "/:cont/:viewed_id/ping/" => "sessions#ping", :as => "viewer_count"
  match "/:cont/:viewed_id/ping/:ident" => "sessions#ping", :as => "ping"
  match "/:cont/:viewed_id/unping/:ident" => "sessions#unping", :as => "unping"
end

web/app/views/layouts/application.html.erb
<% @curr_term ||= get_selected_terms %>
<!DOCTYPE html>
<html>
<head>
  <title><%=APP_NAME%> // <%=controller.human_name.pluralize %> // <%= controller.action_name.humanize %> <%= yield(:title) %></title>
  <% if yield(:enable_small_screen).include?("true") %>
    <%= stylesheet_link_tag    "application", :media => "all and (min-width: 501px)" %>
    <%= stylesheet_link_tag    "small_screen", :media => "screen and (max-width: 500px)" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <% else %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
  <% end %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:script) %>
  <% unless yield(:css).blank? %><style><%= yield(:css) %></style><% end %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link href="<%=ENV['RAILS_RELATIVE_URL_ROOT'] || "" %>/favicon.ico" rel="icon" type="image/x-icon" />
</head>
<body>
  <div>
    <div class="infobox rd-hide">
      <% if @curr_term.blank? %>
        <span class="warning">No active terms. Change the dates or <%= link_to "create a new one", new_term_path %>.</span>
      <% else %>
        <b>active term</b><br/><%=@curr_term.map { |c| c.title }.join(", ") %><br/>
      <% end %>

      <% if @course && @course.term && @course.term.critical? %>
        <span class="warning">Sheets have been printed for this course. Destroy them all before changing anything.</span>
      <% end %>

      <% if (@course.nil? || @course.term.nil?) && @curr_term.any? { |c| c.critical? } %>
        <span class="warning">Careful, current term is critical.</span>
      <% end %>
    </div>

    <h1><%=controller.human_name.pluralize%> // <%= params[:action].humanize %> <%=yield(:title) %></h1>
    <nav class="button-group">
      <%= link_to 'Courses',    courses_path,   :class => "button big" %>
      <%= link_to 'Professors', profs_path,     :class => "button big" %>
      <%= link_to 'Terms',      terms_path,     :class => "button big" %>
      <%= link_to 'Forms',      forms_path,     :class => "button big" %>
      <%= link_to 'Faculties',  faculties_path, :class => "button big" %>
      <%= link_to 'Tutors',     tutors_path,    :class => "button big" %>
      <%= link_to 'Hitmes',     hitme_path,     :class => "button big" %>
    </nav>
  </div>

  <% if flash.any? %>
    <div>
      <% flash.each do |key, msg| %>
        <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_#{key}" %>
      <% end %>
    </div>
  <% end %>

<%= yield %>
  <% if ["edit", "assign_work"].include?(controller.action_name) %><%=render "shared/collision_detection"%><% end %>
</body>
</html>