web/config/routes.rb
# encoding: utf-8

Seee::Application.routes.draw do
  resources :forms do
    member do
      get "/copy_to_current" => "forms#copy_to_current"
      get "/preview" => "forms#preview"
    end
  end

  resources :faculties

  match "/tutors" => "tutors#index"
  resources :courses do
    resources :tutors
    get "/emergency_printing" => "courses#emergency_printing"
    post "/emergency_printing" => "courses#emergency_printing"
    get "/tutors/:id/preview" => "tutors#preview", :as => "tutor_preview"
    post "/tutors/:id/result_pdf" => "tutors#result_pdf", :as => "tutor_result_pdf"
    member do
      post "/add_prof" => "courses#add_prof"
      delete "/drop_prof" => "courses#drop_prof"
      get "/preview" => "courses#preview"
      get "/correlate" => "courses#correlate"
    end
  end

  resources :profs

  resources :terms do
    get "/courses" => "courses#index"
  end

  root :to => "courses#index"

  post "/course_profs/:id/print" => "course_profs#print", :as => :print_course_prof

  # comment image source pass throughs
  get "/pics/:id/download" => "pics#download", :as => :download_pic
  get "/cpics/:id/download" => "CPics#download", :as => :download_cpic


  get "/hitme" => "hitmes#overview"
  get "/hitme/assign_work" => "hitmes#assign_work"
  get "/hitme/cookie_test" => "hitmes#cookie_test"
  get "/hitme/active_users" => "hitmes#active_users"
  post "/hitme/preview_text" => "hitmes#preview_text"
  post "/hitme/save_comment" => "hitmes#save_comment"
  post "/hitme/save_combination" => "hitmes#save_combination"
  post "/hitme/save_final_check" => "hitmes#save_final_check"


  match "/:cont/:viewed_id/ping/" => "sessions#ping", :as => "viewer_count"
  match "/:cont/:viewed_id/ping/:ident" => "sessions#ping", :as => "ping"
  match "/:cont/:viewed_id/unping/:ident" => "sessions#unping", :as => "unping"
end

web/app/controllers/courses_controller.rb
# encoding: utf-8

class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.xml
  def index
    @curr_term ||= view_context.get_selected_terms
    if @curr_term.empty?
      flash[:error] = "Cannot list courses for current term, as there isn’t any current term. Please create a new one first."
      redirect_to :controller => "terms", :action => "index"
      return
    end
    # don’t allow URLs that have the search parameter without value
    if params[:search] && params[:search].empty?
      redirect_to :controller => "courses", :action => "index"
      return
    end

    cond = "term_id IN (?)"
    vals = view_context.get_selected_terms.map { |s| s.id }

    # filter by search term. Provide it as additional array, so the table
    # may hide entries instead of not showing them at all. This allows
    # javascript filtering, even if a query was submitted via HTTP.
    if params[:search]
      @matches = Course.search(params[:search], [:profs, :faculty], [cond], [vals], [:faculty_id, :title])

      # if a search was performed and there is exactly one result go to it
      # directly instead of listing it
      if @matches.size == 1
        redirect_to(@matches.first)
        return
      end
    end

    # find all courses
    @courses = Course.search(nil, [:profs, :faculty], [cond], [vals], [:faculty_id, :title])

    # otherwise, render list of courses
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end

  def search
    @courses = Course.search params[:search]
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
    end
  end

  def correlate
    @course = Course.find(params[:id])
    respond_to do |format|
      format.html
      format.json do
        if [params[:correlate_by], params[:question]].any_nil?
          render :json => "Missing parameters.", :status => :unprocessable_entity
          return
        end

        if params[:correlate_by] == params[:question]
          render :json => "correlate_by and question must be different", :status => :unprocessable_entity
          return
        end

        c = @course.form.get_question(params[:correlate_by])
        q = @course.form.get_question(params[:question])
        if [c,q].any_nil?
          render :json => "Invalid question/correlate_by specified.", :status => :unprocessable_entity
          return
        end

        filter = {:barcode => @course.barcodes }
        data = RT.correlate(@course.form.db_table, c.db_column, q.db_column, filter, true)
        sorted_answers = data.values.map { |v| v.keys }.flatten.uniq.sort_by { |v| v.to_s }
        results = {}
        data.sort_by { |k,v| k.to_s }.each do |k,v|
          k = c.box_text_by_value(k).strip_all_tex if k.is_a?(Integer)
          results[k] = {}
          sorted_answers.each do |kk|
            vv = v[kk] || 0
            kk = q.box_text_by_value(kk).strip_all_tex if kk.is_a?(Integer)
            results[k][kk] = vv
          end
        end
        render :json => results
      end
    end
  end


  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new
    @curr_term ||= view_context.get_selected_terms
    if @curr_term.empty?
      flash[:error] = "Cannot create a new course for current term, as there isn’t any current term. Please create a new one first."
      redirect_to :controller => "terms", :action => "index"
    else
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @course }
      end
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # GET /courses/1/preview
  def preview
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if form_lang_combo_valid? && @course.save
        flash[:notice] = 'Course was successfully created.'
        format.html { redirect_to(@course) }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        flash[:error] = "Selected form and language combination isn’t valid." unless form_lang_combo_valid?
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @course = Course.find(params[:id])
    expire_fragment("preview_courses_#{params[:id]}")

    respond_to do |format|
      checks = form_lang_combo_valid? && !critical_changes?(@course)
      if checks && @course.update_attributes(params[:course])
        flash[:notice] = 'Course was successfully updated.'
        format.html { redirect_to(@course) }
        format.xml  { head :ok }
      else
        if not @course.form.abstract_form_valid?
          flash[:error] = "The selected form is not valid. Please fix it first."
        elsif !form_lang_combo_valid?
          flash[:error] = "The selected form/language combination isn’t valid. #{flash[:error]}"
        elsif critical_changes?(@course)
          flash[:error] = "Some of the changes are critical. Those are currently not allowed."
        else
          flash[:error] = "Could not update the course."
        end

        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id])
    # expire preview cache as well
    expire_fragment("preview_courses_#{params[:id]}")

    unless @course.critical?
      begin
        @course.course_profs.each { |cp| cp.destroy }
        @course.tutors.each { |t| t.destroy }
      end
      @course.destroy
    end

    respond_to do |format|
      flash[:error] = 'Course was critical and has therefore not been destroyed.' if @course.critical?
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end

  # DELETE /courses/drop_prof?course=1&prof=1
  def drop_prof
    @course = Course.find(params[:id])
    unless @course.critical?
      @prof = Prof.find(params[:prof_id])
      @course.profs.delete(@prof)
    end

    respond_to do |format|
      flash[:error] = "Course was critical and therefore prof #{@prof.fullname} has been kept." if @course.critical?
      format.html { redirect_to(@course) }
      format.xml { head :ok }
    end
  end

  def add_prof
    begin
      @course = Course.find(params[:id])
      @prof = Prof.find(params[:courses][:profs])
      @course.profs << @prof

      respond_to do |format|
        format.html { redirect_to(@course) }
        format.xml { head :ok }
      end
    rescue
      flash[:error] = "Couldn’t add prof. Are you sure the course and selected prof exist?"
      respond_to do |format|
        format.html { redirect_to(@course) }
        format.xml  { render :xml => (@course.nil? ? "" : @course.errors),
          :status => :unprocessable_entity }
      end
    end
  end

  def emergency_printing
    @amount = Seee::Config.settings[:emergency_printing_amount]
    @course = Course.find(params[:course_id])
    if request.method.to_s.upcase == "POST"
      exit_codes = []
      @course.course_profs.each do |cp|
        exit_codes << cp.print_execute(@amount)
      end
      if exit_codes.sum == 0
        flash[:notice] = "Should print #{@amount} sheets now for each prof."
      else
        flash[:error] = "Printing returned an error. Call for help."
      end
      redirect_to :course_emergency_printing
    else
      render :action => :emergency_printing
    end
  end

  private
  # looks if critical changes to a course were made and reports them iff
  # the course is critical.
  def critical_changes? course
    # if the term is critical, these fields will not be submitted.
    # supply them from the database instead.
    params[:course][:form_id] ||= course.form.id
    params[:course][:language] ||= course.language
    lang_changed = course.language.to_s != params[:course][:language].to_s
    form_changed = course.form.id.to_s != params[:course][:form_id].to_s
    if course.critical? && (lang_changed || form_changed)
      flash[:error] = "Can’t change the language because the term is critical." if lang_changed
      flash[:error] = "Can’t change the form because the term is critical." if form_changed
      return true
    end
    false
  end

  # Checks if the term actually has the form and if that form
  # actually offers the language selected. Will report any errors.
  def form_lang_combo_valid?
    # if the term is critical, these fields will not be submitted.
    # supply them from the database instead.
    if @course
      params[:course][:form_id] ||= @course.form.id if @course.form
      params[:course][:language] ||= @course.language
      params[:course][:term_id] ||= @course.term.id if @course.term
    end

    # check term has form
    t = Term.find(params[:course][:term_id])
    f = Form.find(params[:course][:form_id])

    unless t && f
      flash[:error] = "Selected term or form not found."
      return false
    end

    unless t.forms.map { |f| f.id }.include?(params[:course][:form_id].to_i)
      flash[:error] = "Form “#{f.name}” (id=#{f.id}) is not " \
                        + "available for term “#{t.title}”"
      return false
    end

    # check form has language
    l = params[:course][:language]
    return true if f.has_language?(l)
    flash[:error] = "There’s no language “#{l}” for form “#{f.name}”"
    false
  end
end

web/app/helpers/courses_helper.rb
# encoding: utf-8

module CoursesHelper
  include FunkyTeXBits

  # finds all available languages in all forms
  def all_langs
    l = []
    Term.all.each do |s|
      s.forms.each { |f| l << f.languages }
    end
    l.flatten.uniq
  end

  # maps given forms to a hash of hashs like:
  # { form_id => { :name => "some form", :langs => [:de, :en] } }
  def map_forms_and_langs(forms)
    h = {}
    forms.each do |f|
      h[f.id] = { :name => f.name, :langs => f.languages }
    end
    h
  end

  # maps all terms to a hashs of hashs like:
  # { term_id => { :title => "WS 10/11", :forms => (see above) } }
  def map_terms_and_forms
    tfl = {}
    Term.all.each do |s|
      tfl[s.id] = { :title => s.title, :forms => map_forms_and_langs(s.forms) }
    end
    tfl
  end

  # returns a JSON version of map_terms_and_forms
  def json_map_sfl
    ActiveSupport::JSON.encode(map_terms_and_forms).html_safe
  end

  def courseShowLink
    link_to("Show “#{@course.title}”", course_path(@course), :class => "button")
  end

  def courseEditLink
    link_to("✎ Edit “#{@course.title}”", edit_course_path(@course), :class => "button primary rd-hide")
  end

  def courseDestroyLink
    link_to_unless(@course.critical?, 'Destroy course', @course, \
      :confirm => "Really destroy course '#{@course.title}'?", \
      :method => :delete,
      :class => "button danger rd-hide") do
      "&nbsp;⚠ Course is critical".html_safe
    end
  end

  def courseLinksForShowPage
    d = []
    d << courseEditLink
    d << courseDestroyLink unless @course.term.critical?
    d << link_to("ϱ Correlate", correlate_course_path(@course), :class => "button")
    d << link_to("⤶ List courses", term_courses_path(@course.term), :class => "button")
    %(<div class="button-group">#{d*""}</div>).html_safe
  end
end

web/app/views/courses/_add_prof.html.erb
<form method="post" action="<%=add_prof_course_path(@course)%>" id="add_prof">
  <input type="hidden" value="<%= form_authenticity_token %>" style="display:none"/>
  <%= collection_select(:courses, :profs, Prof.find(:all, :order => 'surname'), :id, :surnamefirst, { :include_blank => true }, { :class => "combobox" }) %>
  <div class="button-group" style="vertical-align:top">
    <%= submit_tag 'Add professor to course', :class => "button primary" %>
    <%= link_to 'Create New Prof', new_prof_path, :class => "button" %>
  </div>
</form>
<% content_for :script do %>
<script>
  $(document).ready(function() {
    $("form#add_prof").submit(function(e) {
      if(!$("form#add_prof .combobox").val()) {
        $("form#add_prof input.ui-autocomplete-input").focus();
        e.preventDefault();
      }
    });
  });
</script>
<% end %>

web/app/views/courses/_form_lang_select.html.erb
<script type="text/javascript">
  var sfl = <%= json_map_sfl %>;

  function updateSelectors() {
    // gather data derivable from "term"
    // $("#course_form_id > option:selected").text()
    var availForms = sfl[$("#course_term_id").val()].forms;

    // find current settings of "form"
    var formOldName = $("#course_form_id > option:selected").text();

    // rebuild forms drop down
    var cfi = $("#course_form_id");
    cfi.html("");
    $.each(availForms, function (fid, data) {
      cfi.append($("<option />").val(fid).text(data.name).attr("selected", formOldName == data.name));
    });

    // gather data derivable from "form"
    var langs = availForms[$("#course_form_id").val()].langs;

    // find current settings of "lang"
    var langOld = $("#course_language > option:selected").text();

    // rebuild langs drop down
    var cl = $("#course_language");
    cl.html("");
    $.each(langs, function (index, lang) {
      cl.append($("<option />").val(lang).text(lang).attr("selected", langOld == lang));
    });
  }

  $(document).ready(function() {
    updateSelectors();
  });
</script>

web/app/views/courses/correlate.html.erb
<% content_for :script, javascript_include_tag("excanvas.js") %>
<% content_for :script, javascript_include_tag("visualize.jQuery.js") %>
<% content_for :script do %>
<script>
  var root = "<%=j url_for(:only_path => false) %>";
  var question = <%=(params[:question] ? %("#{j params[:question]}") : "null").html_safe %>;
</script>
<% end %>
<% content_for :script, javascript_include_tag("correlate.js") %>

<%
  links = %(<div class="button-group">)
  links << (link_to "Return to #{@course.title}", @course, :class => "button")
  links << %(</div>)
  links = links.html_safe
%>

<div>
  <h2>Correlate <%=@course.title %> (<%=@course.term.title %>)</h2>
  <%=links%>
  <br style="clear:both"/>

  <label for="correlate_by">Select question to correlate by:</label><br/>
  <select id="correlate_by">
    <option value="">Please select</option>
    <%=
      o = ActiveSupport::SafeBuffer.new
      @course.form.sections.each do |s|
        o << %(<optgroup label="#{h s.any_title}">).html_safe
        s.questions.each do |q|
          next if q.multi? || q.comment?
          sel = params[:correlate_by] == q.db_column ? %(selected="selected") : ""
          o << %(<option value="#{h q.db_column}" #{sel}>).html_safe
          o << q.text.strip_all_tex
          o << %(</option>).html_safe
        end
        o << %(</optgroup>).html_safe
      end
      o
    %>
  </select>
</div>



<div>
  <%=links%>
</div>

web/app/views/courses/emergency_printing.html.erb
<% content_for :title, "“#{@course.title}”" %>
<% content_for :enable_small_screen, "true" %>
<% content_for :css, "#print#{@course.id} { width: 22rem }" %>


<div>
  <ul>
    <li><b>Click and hold</b> for five seconds to start printing.</li>
    <li>Prints <%=@amount%> sheets for each prof: <%=@course.profs.map { |p| p.fullname }.join(", ")%></li>
    <li>If you need more than <%=@amount%> sheets, wait until the page reloads, then click again.</li>
  </ul><br/>
  <%= render 'shared/hold_button', :url => course_emergency_printing_path(@course), :name => "print #{@course.course_profs.size}×#{@amount} sheets NOW", :id => "print#{@course.id}", :button => true, :classes => "primary big" %>

  <br/><br/>
  <%=link_to "return to course", @course, :class => "button" %>
</div>

web/app/views/courses/index.html.erb
<% content_for :enable_small_screen, "true" %>

<div>
  <h2>Courses in <%=Term.currently_active.map { |t| t.title }.join(", ")%></h2>

  <div class="button-group rd-hide">
    <%=link_to 'Create new Course', new_course_path, :class => "button"%>
    <%=link_to 'Show courses from other terms', terms_path, :class => "button"%>
  </div>
  <span class="rd-hide"><br/><br/></span>

  <%=render "shared/tablemagic", :search => true %>
  <table id="tablemagic" style="min-width:70em; width:100%" class="rd-hide-2 rd-hide-3 rd-hide-4 rd-hide-6">
    <thead>
    <tr>
      <% ["Title", "Students", "Evaluated by", "Profs", "Description", "Faculty"].each do |x| %>
        <th><%=x%></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr<%=@matches && !@matches.include?(course) ? %( style="display:none").html_safe : "" %>>
          <td>
            <% unless course.no_censoring? %>
              <span title="Parts of this course will be censored." style="cursor:help">☹</span>
            <% end %>
            <%  xx, need, have = course.enough_censored_parts_in_comments? %>
            <% unless xx  %>
              <span title="<%=need%> profs want cencoring, but only <%=have%> censor blocks found.">Censoring broken. Fix it!</span>
            <% end %>
            <%= link_to course.title.truncate(50), course, :title => course.title %>
          </td>
          <td><%=course.students || "MISSING" %></td>
          <td><%=course.evaluator %></td>
          <td><%=course.profs.collect { |p| p.lastname }.join(", ") %></td>
          <td><%=course.description %></td>
          <td><%=course.faculty.shortname %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div>
  <div class="button-group">
    <%=link_to 'Create new Course', new_course_path, :class => "button"%>
    <%=link_to 'Show courses from other terms', terms_path, :class => "button"%>
  </div>
</div>

web/app/views/courses/new.html.erb
<%= render "courses/form_lang_select" %>

<%= form_for(@course) do |f| %>
  <div class="group">
    <h2>Create new course</h2>
    <%= render "shared/error_messages", :model => @term %>

    <table>
      <% for item in
        [
          [f.label(:term_id),                           f.collection_select(:term_id, Term.all.reverse, :id, :title, {}, {:onchange => "updateSelectors();" }), "required"],
          [f.label(:title),                             f.text_field(:title), "required"],
          [f.label(:students),                          f.text_field(:students), "numeric"],
          [f.label(:form_id),                           f.collection_select(:form_id, Form.all, :id, :name, {}, {:onchange => "updateSelectors();" }), "required"],
          [f.label(:language),                          f.collection_select(:language, all_langs, :to_sym, :to_s), "required"],
          [f.label(:evaluator, "Evaluated by"),         f.text_field(:evaluator)],
          [f.label(:fscontact, "FS Account OR Email"),  f.text_field(:fscontact), "may be omitted if “Evaluated by” is the account name"],
          [f.label(:description),                       f.text_field(:description), "Multi-use field (date, status, etc.)"],
          [f.label(:faculty_id),                        f.collection_select(:faculty_id, Faculty.all, :id, :longname), "required"]
        ]
      %>
        <tr>
          <th><%= item.shift %></th>
          <td><%= item.shift %></td>
          <% for data in item do %> <td><%=h data %></td> <% end %>
        </tr>
      <% end %>
    </table>

    <div class="button-group">
      <%= f.submit "Create new course", :disable_with => "Saving…", :class => "button primary" %>
      <%= link_to "Cancel", Course, :class => "button" %>
    </div>
  </div>
<% end %>

web/app/views/courses/preview.html.erb
<div>
  <h2>Previewing <%=@course.title %></h2>
  <div class="button-group">
    <%= courseShowLink %>
    <%= courseEditLink %>
  </div>
</div>

<%= render "shared/preview_big", :text => @course.summary %>

web/app/views/courses/show.html.erb
<% content_for :enable_small_screen, "true" %>
<% content_for :title, "“#{@course.title}”" %>


<div>
  <div class="rd-hide">
    <h2><%=@course.title %> (<%=@course.term.title %>)</h2>
    <%= courseLinksForShowPage %>
    <br style="clear:both"/>
  </div>

  <table class="two-tables-left">
    <tr><th colspan="2" style="font-size:120%">master data</th></tr>
    <%
      comment_link = link_to "#{@course.c_pics.size} comments (#{number_to_percentage(@course.c_pics.size/@course.returned_sheets.to_f*100, :precision => 0)})", (edit_course_path(@course) + "#commentfield")
      comment_returned = "#{@course.returned_sheets} returned (#{number_to_percentage(@course.return_quota*100, :precision => 0)})"
      spacer = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
      stud_returned = "#{@course.students} #{spacer} #{comment_returned} #{spacer} #{comment_link}".html_safe
    %>
    <% for item in [
        [:title,    @course.title],
        [:term,     link_to(@course.term.title, edit_term_path(@course.term))],
        [:faculty,  link_to(@course.faculty.longname, edit_faculty_path(@course.faculty))],
        [:form,     link_to("#{@course.form.name} (language: #{@course.language})", @course.form)],
        [:students, @course.returned_sheets? ? stud_returned : @course.students],
        [:note,     @course.note]] %>
      <tr>
        <th><%=Course.human_attribute_name(item.shift) %></th>
        <% item.each { |d| %> <td><%=d %></td> <% } %>
      </tr>
    <% end %>
  </table>

  <table class="two-tables-right">
    <tr><th colspan="2" style="font-size:120%">adminstrative data</th></tr>
    <% for item in [
        [:evaluator,      @course.evaluator],
        [:fscontact,      @course.fscontact],
        [:email,          @course.fs_contact_addresses_array.map { |a| mail_to(a) }.join(", ").html_safe],
        [:description,    @course.description]] %>
      <tr>
        <th><%=Course.human_attribute_name(item.shift) %></th>
        <% item.each { |d| %> <td><%=d %></td> <% } %>
      </tr>
    <% end %>
    <% unless @course.mails_sent.blank? %>
      <tr>
        <th><%=Course.human_attribute_name(:mails_sent) %></th>
        <td><%=@course.mails_sent%></td>
      </tr>
    <% end %>
  </table>
</div>

<% okay, need, have = @course.enough_censored_parts_in_comments? %>
<% unless okay %>
  <div>
    <p class="error">
      <b>Comments aren’t censored enough</b><br/>
      Apparenty at least <%=need%> Prof(s) want their comments censored. However, I only found <%=have%> censored blocks. Go, censor, NOW! The results will <i>not</i> render. If a prof has no comments, include it like this:
<pre>\CENSORED
\UNCENSORED</pre>
    </p>
  </div>
<% end %>

<div class="rd-hide">
  <h3><%=latex_logo%> Preview</h3>
  <div class="preview">
    <%= render "shared/preview", :text => @course.summary %>
  </div>
  <%= link_to 'Show preview in full', preview_course_path(@course), :class => "button" %>
</div>


<%
  unknown_censor = @course.profs.select { |p| p.censor_unknown? }.map { |p| "Prof. #{p.lastname}" }
  unknown_censor += @course.tutors.select { |t| t.censor_unknown? }.map { |t| "Tutor #{t.abbr_name}" }
  if unknown_censor.any?
%>
<div>
  <p class="warning">
    <b>Unknown Censor status</b><br/>The following people have unknown censoring information. <i>All</i> of their contents will be printed.
    <ul>
      <% unknown_censor.each do |cc| %>
        <li><%=cc%></li>
      <% end %>
    </ul>
  <p>
</div>
<% end %>

<div>
  <h3>Professors</h3>
  <% if @course.profs.empty? %><span class="warning">No professors have been specified so far. The course cannot be evaluated and no sheets will be printed until at least one professor is added.</span><% end %>

  <table class="rd-hide-2 rd-hide-3 rd-hide-4">
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>ID/Barcode</th>
      <th>Censoring</th>
      <th colspan="3">Actions</th>
    </tr>
    <% @course.course_profs.each do |cp| %>
    <tr>
      <td><%=link_to cp.prof.fullname, edit_prof_path(cp.prof) %></td>
      <td><%=cp.prof.email %></td>
      <td><%=cp.id %></td>
      <td><%=cp.prof.censor %></td>
      <td>
        <% if @course.returned_sheets? %>
          <%="Can’t print, has returned sheets."%>
        <% else %>
          <%= render 'shared/hold_button', :url => print_course_prof_path(cp), :name => "print (evil)", :id => "print#{cp.id}" %>
        <% end %>
      </td>
      <% unless @course.critical? %>
        <td class="rd-hide">
          <%= link_to 'Destroy', { :action => 'drop_prof', :id => @course, :prof_id => cp.prof},
          :confirm => "Really remove #{cp.prof.fullname}? Don't continue if sheets have been printed.", :method => :delete %>
        </td>
      <% end %>
    </tr>
    <% end %>
  </table>

  <div class="rd-hide"><%=render "add_prof"%></div>
</div>


<div>
  <h3>Tutors</h3>
  <% unless @course.tutors.empty? %>
    <table>
      <tr>
        <th>Name</th>
        <th># Comments</th>
        <th># Sheets</th>
        <th>Censoring</th>
        <th class="rd-hide">Actions</th>
      </tr>
      <% @course.tutors.each do |tutor| %>
      <tr>
        <td><%= link_to tutor.abbr_name, edit_course_tutor_path(@course, tutor) %></td>
        <td style="text-align:right"><%= tutor.pics.count %></td>
        <td style="text-align:right"><%= tutor.returned_sheets %></td>
        <td><%= tutor.censor %></td>
        <td class="rd-hide">
        <% unless tutor.critical? %>
          <%= link_to 'Destroy', {:controller => 'tutors', :id => tutor,
            :course_id => @course.id, :action => 'destroy'},
            :confirm => "Really remove tutor #{tutor.abbr_name}? (Order changes after destruction. Don't continue if sheets have been printed.)",
            :method => :delete %></td>
        <% end %>
        <% if tutor.returned_sheets >= Seee::Config.settings[:minimum_sheets_required] %>
          <a class="hold"
            data-time="5"
            data-onlyonce="true"
            data-post="<%= form_authenticity_token%>"
            data-url="<%=course_tutor_result_pdf_path(tutor.course, tutor)%>"><noscript>(needs JS)</noscript> result.pdf (slow)</a>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
    <% end %>
    <div class="rd-hide">
      <%= render @tutor = Tutor.new, :button_name => 'Add Tutor(s)' %>
    </div>
</div>

<div>
  <%= courseLinksForShowPage %>
</div>