web/config/routes.rb
# encoding: utf-8

Seee::Application.routes.draw do
  resources :forms do
    member do
      get "/copy_to_current" => "forms#copy_to_current"
      get "/preview" => "forms#preview"
    end
  end

  resources :faculties

  match "/tutors" => "tutors#index"
  resources :courses do
    resources :tutors
    get "/emergency_printing" => "courses#emergency_printing"
    post "/emergency_printing" => "courses#emergency_printing"
    get "/tutors/:id/preview" => "tutors#preview", :as => "tutor_preview"
    post "/tutors/:id/result_pdf" => "tutors#result_pdf", :as => "tutor_result_pdf"
    member do
      post "/add_prof" => "courses#add_prof"
      delete "/drop_prof" => "courses#drop_prof"
      get "/preview" => "courses#preview"
      get "/correlate" => "courses#correlate"
    end
  end

  resources :profs

  resources :terms do
    get "/courses" => "courses#index"
  end

  root :to => "courses#index"

  post "/course_profs/:id/print" => "course_profs#print", :as => :print_course_prof

  # comment image source pass throughs
  get "/pics/:id/download" => "pics#download", :as => :download_pic
  get "/cpics/:id/download" => "CPics#download", :as => :download_cpic


  get "/hitme" => "hitmes#overview"
  get "/hitme/assign_work" => "hitmes#assign_work"
  get "/hitme/cookie_test" => "hitmes#cookie_test"
  get "/hitme/active_users" => "hitmes#active_users"
  post "/hitme/preview_text" => "hitmes#preview_text"
  post "/hitme/save_comment" => "hitmes#save_comment"
  post "/hitme/save_combination" => "hitmes#save_combination"
  post "/hitme/save_final_check" => "hitmes#save_final_check"


  match "/:cont/:viewed_id/ping/" => "sessions#ping", :as => "viewer_count"
  match "/:cont/:viewed_id/ping/:ident" => "sessions#ping", :as => "ping"
  match "/:cont/:viewed_id/unping/:ident" => "sessions#unping", :as => "unping"
end

web/app/views/shared/_aceify_textareas.html.erb
<% line_offset ||= 0 %>
<% mode ||= "latex" %>
<% content_for :script, javascript_include_tag("ace/ace") %>
<% content_for :script, javascript_include_tag("ace/mode-#{mode}") if File.exists?("#{RAILS_ROOT}/app/assets/javascripts/ace/mode-#{mode}.js") %>
<% content_for :script, %(<script>
  var line_offset_number = #{line_offset};
  var ace_mode = "#{mode}";
  var aceAutosize = #{defined?(autosize) && autosize ? "true" : "false"};
</script>).html_safe %>
<% content_for :script, javascript_include_tag("aceify-textareas") %>

web/app/views/shared/_collision_detection.html.erb
<div id="darkened"></div>

<noscript><div class="group warning">You have <b>disabled JavaScript</b>. You and others can’t be notified if they edit this page at the same time. This might lead to <b>collisions</b> as they are not handled in any way. User who hits the save button last wins.</div></noscript>

<div id="collision-warning" class="warning hidden">This page is currently opened more than once. This might lead to your changes being overwritten. If you opened this window just now, please close it. Otherwise talk to each other and solve this.<br/><strong>Viewers:</strong><br/><span id="viewers"></span><br/><a onclick="setUsernameCookie(); event.stopPropagation();">Set Your Username</a></div>

<script>
  var   ping = "<%=  ping_path(params[:controller], params[:id], "PLACEHOLDER")%>";
  var unping = "<%=unping_path(params[:controller], params[:id], "PLACEHOLDER")%>";
</script>
<%= javascript_include_tag("viewer_count") %>

web/app/views/shared/_comment_pic.html.erb
<% path = pic.is_a?(CPic) ? download_cpic_url(pic) : download_pic_url(pic) %>

<figure title="<%=pic.text%>">
  <%= (pic.source ? %(<span data-url="#{path}" class="hold">) : %(<span>)).html_safe %>
    <img src="<%=comment_image_link %>/<%= course.term.dir_friendly_title + '/' + pic.basename %>" />
  </span>
</figure>

web/app/views/shared/_error_messages.html.erb
<% if model && model.errors.any? %>
<div>
  <div class="errorExplanation" id="errorExplanation">
    <h3><%= pluralize(model.errors.size, "error") %> <%= model.errors.size == 1 ? "needs" : "need" %> to be fixed.</h3>
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

web/app/views/shared/_hold_button.html.erb
<a
  title="Click and hold for five seconds to activate."
  class="hold <%=defined?(button) && button ? "button" : ""%>"
  data-time="5"
  data-group="<%=id%>"
  data-onlyonce="true"
  data-post="<%= form_authenticity_token%>"
  data-url="<%=url%>"><noscript>(needs JS)</noscript> <%=name%></a>

web/app/views/shared/_loading.html.erb
<span class="loading">
      .-""-.
⑊    /      \
│⑊~~~~~~~│   ;
│ ⑊      │  /
│  ⑊     │-'
│   ⑊    │       drink responsibly while
│    ⑊   │       waiting for this preview
│     ⑊  │       to be rendered for you.
│      ⑊ │
│       ⑊│
└────────┘
 GnT-Eval</span>

web/app/views/shared/_preview.html.erb
<%
# this is a general preview shared view. Hand in the text that should
# be previewed as a local variable, like this:
#    render "shared/preview", :text => TEXT
# Optionally hand in the object, so it gets auto expired. Otherwise
# you need to call expire_fragment manually.
#    render "shared/preview", :text => TEXT, :obj => OBJECT
# You can also disable caching altogether by passing :disable_cache => true
%>

<%

key = (defined?(obj) && obj) ? obj : "preview_#{params[:controller]}_#{params[:id]}"
enable_cache = !defined?(disable_cache) || !disable_cache

optional_cache(key, enable_cache) do %>
  <%
    failed, exitcodes, error, base64, dim = texpreview(text)
    is_img = !failed && !base64.blank?
  %>

  <%# required for properly previewing in form editor %>
  <%= "<div>".html_safe unless is_img %>

  <% if failed || base64.nil? %>
    <span class="error">An error occurred while rendering the preview. Most likely, you have a typo in the TeX code somewhere. Scroll down to see what TeX has to say about this.</span><br/><br/>
    EXIT CODES: <%= exitcodes.join(", ") %>
    <br/><div class="pre"><%= error.html_safe %></div>
  <% end %>

  <% if !base64.nil? && base64.empty? %>
    <span class="info">Nothing to display.</span>
  <% end %>

  <%= "</div>".html_safe unless is_img %>

  <%= %(<img width="#{dim[0]}" height="#{dim[1]}" class="no-shadow" src="data:image/png;base64,#{base64}"/>).html_safe if is_img %>
<% end %>

web/app/views/shared/_preview_ajax.html.erb
<%
# Works just like preview_big, except that the actual rendering
# is executed via AJAX so it doesn’t stall the page load. For
# this to work the controller needs to have a preview method that
# renders the shared/preview.html.erb partial.
# Use it like this:
#   render "shared/preview_ajax", :preview_url => preview_form_path(@form)
#
# The way actually taken looks something like this:
# 1. preview_ajax requests given preview_url (preview_form_path)
# 2. form controller renders partial view shared/preview
# 3. shared/preview calls the "texpreview" helper method for this controller
# 4. forms_helper.rb#texpreview actually renders the preview.
#
# Note that if only basic text rendering services are required, the
# controller will usually hand down the text directly in step 2 and so
# will shared/preview in step 3. The helper file then includes
# FunkyTeXBits which also have a texpreview(text) method.
%>

<div>
  <h3><%=latex_logo%> Preview</h3>

  <div class="preview large">
    <script>
      var e = $("script:last").parent(".preview");
      e.load("<%=preview_url%>", function() {
        e.animate({height:"1000px"}, 1000, function() {
          e.removeClass("loading").css("height", "auto");
        });
        e.siblings(".loading").slideUp();
      });
    </script>
  </div>
  <%=render "shared/loading"%>
</div>

web/app/views/shared/_preview_big.html.erb
<div>
  <h3><%=latex_logo%> Preview</h3>
  <div class="preview large">
    <%= render "shared/preview", :text => text %>
  </div>
</div>

web/app/views/shared/_tablemagic.html.erb
<%# adds filtering and sorting goodies to up to one table per page. %>
<%# Use it like this: %>
<%# render "shared/tablemagic" %>
<%# <table id="tablemagic" style="min-width:123em"> … %>




<%# If search is also implemented on the server side you can pass %>
<%# :search => true; then the form will be submitable using GET and %>
<%# the ?search= URL parameter. %>

<% clear=%(<a href="#" onclick="var f=$('#filterfield'); f.val(''); f.trigger('change'); return false;" class="button">Clear</a>).html_safe %>

<% if defined?(search) && search %>
  <%= form_tag "", :method => 'get', :class => "singleline" do %>
    <%= text_field_tag :search, params[:search],
          :placeholder => "Filter…",
          :type => "search",
          :id => "filterfield",
          :style => "margin-right:.2rem"
      %>
    <% if params[:search] %>
      <a href="<%=request.path%>" class="button">Clear</a>
    <% else %>
      <%=clear%>
    <% end %>
  <% end %>
<% else %>
  <input type="text" id="filterfield" placeholder="Filter…"/>
  <%=clear%>
<% end %>

web/app/views/shared/main_menu.html.erb
<% @curSem = Semester.all.find{ |s| s.now? } %>

<fieldset class="main_menu">
  <legend><b>main menu</b></legend>
  <%= link_to 'Courses', 	    :controller => "courses",     :action => "index" %> |
  <%= link_to 'Professors', 	:controller => "profs", 	    :action => "index" %> |
  <%= link_to 'Semesters', 	  :controller => "semesters",   :action => "index" %> |
  <%= link_to 'Forms', 		    :controller => "forms", 	    :action => "index" %> |
  <%= link_to 'Faculties', 		:controller => "faculties", 	:action => "index" %> |
  <%= link_to 'Tutors', 		  :controller => "tutors", 	    :action => "index" %>

  <span style="float:right">&nbsp;<%=h @curSem.title %></span>

  <% if @course && @course.semester && @course.semester.critical? %>
    <span class="warning">Careful, sheets for this course have been printed.</span>
 <% end %>

   <% if (@course.nil? || @course.semester.nil?) && @curSem.critical? %>
    <span class="warning">Careful, current semester is critical.</span>
 <% end %>
</fieldset>