web/config/routes.rb
# encoding: utf-8

Seee::Application.routes.draw do
  resources :forms do
    member do
      get "/copy_to_current" => "forms#copy_to_current"
      get "/preview" => "forms#preview"
    end
  end

  resources :faculties

  match "/tutors" => "tutors#index"
  resources :courses do
    resources :tutors
    get "/emergency_printing" => "courses#emergency_printing"
    post "/emergency_printing" => "courses#emergency_printing"
    get "/tutors/:id/preview" => "tutors#preview", :as => "tutor_preview"
    post "/tutors/:id/result_pdf" => "tutors#result_pdf", :as => "tutor_result_pdf"
    member do
      post "/add_prof" => "courses#add_prof"
      delete "/drop_prof" => "courses#drop_prof"
      get "/preview" => "courses#preview"
      get "/correlate" => "courses#correlate"
    end
  end

  resources :profs

  resources :terms do
    get "/courses" => "courses#index"
  end

  root :to => "courses#index"

  post "/course_profs/:id/print" => "course_profs#print", :as => :print_course_prof

  # comment image source pass throughs
  get "/pics/:id/download" => "pics#download", :as => :download_pic
  get "/cpics/:id/download" => "CPics#download", :as => :download_cpic


  get "/hitme" => "hitmes#overview"
  get "/hitme/assign_work" => "hitmes#assign_work"
  get "/hitme/cookie_test" => "hitmes#cookie_test"
  get "/hitme/active_users" => "hitmes#active_users"
  post "/hitme/preview_text" => "hitmes#preview_text"
  post "/hitme/save_comment" => "hitmes#save_comment"
  post "/hitme/save_combination" => "hitmes#save_combination"
  post "/hitme/save_final_check" => "hitmes#save_final_check"


  match "/:cont/:viewed_id/ping/" => "sessions#ping", :as => "viewer_count"
  match "/:cont/:viewed_id/ping/:ident" => "sessions#ping", :as => "ping"
  match "/:cont/:viewed_id/unping/:ident" => "sessions#unping", :as => "unping"
end

web/app/models/hitme.rb
class Hitme < ActiveRecord::Base
  TYPING = 0
  PROOFREADING = 1
  COMBINING = 2
  FINALCHECK = 3
  DONE = 4

  def self.step_to_text(step)
    case step
      when nil then "typing"
      when Hitme::TYPING then "typing"
      when Hitme::PROOFREADING then "proofreading"
      when Hitme::COMBINING then "combining"
      when Hitme::FINALCHECK then "final checking"
      when Hitme::DONE then "about to finish"
      else raise("Undefined step: #{step}")
    end
  end


  # returns all comments that are currently at the specified step.
  # Includes comments that are being worked on right now.
  def self.get_all_comments_by_step(step)
    step = [nil, Hitme::TYPING] if step == Hitme::TYPING
    all = CPic.joins(:course).where("courses.term_id" => self.curr_term, "step" => step)
    all += Pic.joins(:course).where("courses.term_id" => self.curr_term, "step" => step)
    logger.debug "Found #{all.size} comments in step #{step}"
    all
  end

  # find a comment someone can work on.
  def self.get_workable_comment_by_step(step, skip = 0)
    all = self.get_all_comments_by_step(step)
    self.get_workable_sample(all, skip)
  end


  def self.get_combinable(skip = 0)
    all = self.get_all_combinable_courses + self.get_all_combinable_tutors
    self.get_workable_sample(all, skip)
  end

  def self.get_all_combinable_courses
    c = Course.includes(:c_pics).where("term_id" => self.curr_term).to_a
    # remove all courses without images
    c.reject! { |x| x.c_pics.none? }
    # remove course if there are any images below COMBINING
    c.reject! { |x| x.c_pics.any? { |p| p.step < Hitme::COMBINING } }
    # remove all tutors if there ALL images are above COMBINING
    c.reject! { |x| x.c_pics.all? { |p| p.step > Hitme::COMBINING } }
    # remove courses that don’t have any text comments
    c.reject! { |x| x.c_pics.all? { |p| p.text.blank? } }
    logger.debug "Found #{c.size} combineable courses"
    c
  end

  def self.get_all_combinable_tutors
    c = Tutor.joins(:course).includes(:pics).where("courses.term_id" => self.curr_term).to_a
    # remove all tutors without images
    c.reject! { |x| x.pics.none? }
    # remove all tutors if there are any images below COMBINING
    c.reject! { |x| x.pics.any? { |p| p.step < Hitme::COMBINING } }
    # remove all tutors if there ALL images are above COMBINING
    c.reject! { |x| x.pics.all? { |p| p.step > Hitme::COMBINING } }
    # remove tutors that don’t have any text comments
    c.reject! { |x| x.pics.all? { |p| p.text.blank? } }
    logger.debug "Found #{c.size} combinale tutors"
    c
  end


  def self.get_final_checkable(skip = 0)
    # locking is only happening for the course. Hope there will be no
    # collisions for the tutors
    self.get_workable_sample(self.get_all_final_checkable, skip)
  end


  def self.get_all_final_checkable
    c = Course.includes(:c_pics).where("term_id" => self.curr_term).to_a
    c.reject! { |x| x.c_pics.none? && x.tutors.all? { |t| t.pics.none? } }
    # remove course if there are course-images below FINALCHECK
    c.reject! { |x| x.c_pics.any? { |p| p.step < Hitme::FINALCHECK } }
    # remove course if there are tutor-images below FINALCHECK
    c.reject! { |x| x.tutors.any? { |t| t.pics.any? { |p| p.step < Hitme::FINALCHECK } } }
    # remove course if all images are above FINALCHECK
    c.reject! do |x|
      a = x.c_pics.all? { |p| p.step > Hitme::FINALCHECK }
      b = x.tutors.all? { |t| t.pics.all? { |p| p.step > Hitme::FINALCHECK } }
      a && b
    end
    logger.debug "Found #{c.size} final checkables"
    c
  end



  private
  def self.curr_term
    Term.currently_active.map(&:id)
  end

  def self.get_workable_sample(all, skip)
    raise "Expected an array, but got #{all.class}" unless all.is_a?(Array)
    while not (workon = all.sample).nil?
      if Hitme.is_being_worked_on(workon)
        logger.debug "#{workon.class}=#{workon.id} is being worked on. Skipping."
        # workon is already being worked on by someone else, remove it
        # from the array so it’s not picked again. Deliberately not using
        # all.delete because it may invoke Rails deleting the object.
        all -= [workon]
        next
      end

      if (workon.is_a?(Course) ? workon.id : workon.course.id) == skip
        logger.debug "#{workon.class}=#{workon.id} skipped, because user marked it as so."
        all -= [workon]
        next
      end
      return workon
    end
    nil
  end

  # Checks if the given object is currently being worked on.
  def self.is_being_worked_on(obj)
    # be a little more generous in case the connection is flaky
    Session.unscoped
      .where(["updated_at > ?", 1.minutes.ago])
      .exists?(:cont => obj.class.to_s.pluralize.downcase, :viewed_id => obj.id)
  end
end

web/app/controllers/hitmes_controller.rb
# encoding: utf-8

class HitmesController < ApplicationController
  def overview
    render :action => "overview"
  end

  def active_users
    render :partial => "active_users"
  end

  def assign_work
    if (cookies["username"] || "").gsub(/[^a-z0-9_\s-]/i, "").blank?
      flash[:error] = "No username set, cannot continue."
      redirect_to :action => "overview"
      return
    end

    skip = cookies[:skip_course].to_i

    # randomize type of work first, then try to get a random chunk for
    # the selected type. If there isn’t one, try the next type until
    # work is found or all options are depleted. This setup avoids
    # finding /all/ available chunks while still being kinda-random.
    @workon = nil
    is_final_checkable = false
    (0..3).to_a.shuffle.each do |x|
      case x
        when 0 then @workon = Hitme.get_workable_comment_by_step(0, skip)
        when 1 then @workon = Hitme.get_workable_comment_by_step(1, skip)
        when 2 then @workon = Hitme.get_combinable(skip)
        when 3 then
          # required because final checkables and course combines are
          # the same class
          @workon = Hitme.get_final_checkable(skip)
          is_final_checkable = !@workon.nil?
      end
      break unless @workon.nil?
    end

    @workon.freeze

    if @workon.nil?
      flash[:notice] = "Currently no available tasks. Try again later."
      redirect_to :action => "overview"
    else
      # make collision detection happy
      params[:controller] = @workon.class.to_s.pluralize.downcase
      params[:id] = @workon.id

      @ident = precreate_session(@workon)

      case @workon.class.to_s
        when "Pic"  then render :action => "type_proofread"
        when "CPic" then render :action => "type_proofread"
        when "Tutor"  then render :action => "combine"
        when "Course" then
          render :action => is_final_checkable ? "final_check" : "combine"
        else raise "not implemented"
      end
    end
  end

  # handles updating text and step for comment typing and proofreading.
  # automatically redirects the user according to the action chosen.
  def save_comment
    x = case params[:type]
      when "CPic" then CPic.find(params[:id])
      when  "Pic" then Pic.find(params[:id])
      else nil
    end

    if params[:cancel] || x.nil?
      flash[:error] = "The comment image in question could not be found." if x.nil?
      redirect_to :action => "overview"

    elsif params[:save_and_skip]
      x.text = params[:text]
       # initialize step to 0, otherwise the validations might fail
      x.step ||= 0
      flash[:error] = "Your changes could not be saved. Please investigate." if not x.save
      redirect_to :action => "assign_work"

    elsif params[:save_and_quit] || params[:save_and_work]
      x.text = params[:text]

      next_step = { nil => Hitme::PROOFREADING, Hitme::TYPING => Hitme::PROOFREADING, Hitme::PROOFREADING => Hitme::COMBINING }
      if next_step.keys.include?(x.step)
        x.step = next_step[x.step]
        x.step = Hitme::DONE if x.step == Hitme::COMBINING && x.text.blank?
      else
        flash[:warning] = "Could not advance step, there might have been a collision. You shouldn’t worry too much about it though."
      end

      if x.save
        flash[:notice] = "Changes have been saved."
      else
        flash[:error] = "Your changes could not be saved. Please investigate before continuing."
      end

      redirect_to :action => params[:save_and_quit] ? "overview" : "assign_work"

    else
      flash[:error] = "Invalid action given. Your comment was not saved."
      redirect_to :action => "overview"
    end

    remove_session(x)
  end


  def save_combination
    x = case params[:type]
      when "Course" then Course.find(params[:id])
      when "Tutor"  then Tutor.find(params[:id])
      else nil
    end

    if params[:cancel] || x.nil?
      flash[:error] = "Could not find course/tutor with given ID." if x.nil?
      redirect_to :action => "overview"

    elsif params[:save_and_skip]
      x.comment = params[:text]
      flash[:error] = "Your combination/merge could not be saved. Please investigate." if not x.save
      redirect_to :action => "assign_work"

    elsif params[:save_and_quit] || params[:save_and_work]
      x.comment = params[:text]

      if x.save
        flash[:notice] = "Changes have been saved."
        # advance all comments by one step
        pics = x.respond_to?("c_pics") ? x.c_pics : x.pics
        flash[:warning] = "Could not advance to the next step." unless pics.update_all(:step => Hitme::FINALCHECK)
      else
        flash[:error] = "Your changes could not be saved. Please investigate before continuing."
      end

      redirect_to :action => params[:save_and_quit] ? "overview" : "assign_work"

    else
      flash[:error] = "Invalid action given. Your comment was not saved."
      redirect_to :action => "overview"
    end

    remove_session(x)
  end


  def save_final_check
    course = Course.find(params[:id])
    errs = []
    step_warn = false

    errs << "Couldn’t find specified course. Saving failed." unless course
    if course
      course.comment = params[:course]
      unless course.save
        errs << "Couldn’t save course."
      else
        step_warn = true unless course.c_pics.update_all(:step => Hitme::DONE)
      end
    end

    params[:tutor].each do |tut_id, text|
      logger.info "Processing tutor=#{tut_id}"
      tutor = Tutor.find(tut_id)
      unless tutor
        errs << "Couldn’t find specified tutor. Saving failed."
        next
      end
      tutor.comment = text
      unless tutor.save
        errs << "Couldn’t save tutor #{tutor.abbr_name}."
      else
        step_warn = true unless tutor.pics.update_all(:step => Hitme::DONE)
      end
    end if params[:tutor]

    remove_session(course)

    if errs.empty?
      flash[:notice] = "Save successful." unless params[:save_and_skip]
      if params[:save_and_skip] || params[:save_and_work]
        redirect_to :action => "assign_work"
      else  # params[:save_and_quit] and others
        redirect_to :action => "overview"
      end
    else
      flash[:error] = errs.join("<br />").html_safe
      redirect_to :action => "overview"
    end
  end


  def preview_text
    text = params[:text]
    text = params[:listify].to_s == "true" ? view_context.text_to_list(text) : text
    render :partial => "shared/preview", :locals => {
      :text => text,
      :disable_cache => true}
  end


  def cookie_test
    render :json => cookies[:testcookie] == "test value"
  end

  private
  def precreate_session(workon)
    # golf via http://stackoverflow.com/a/88341/1684530
    ident = (0...9).map{65.+(rand(26)).chr}.join.downcase

    x = Session.new(:cont => workon.class.to_s.pluralize.downcase, :viewed_id => workon.id)
    x.ident = ident
    x.agent = request.env['HTTP_USER_AGENT']
    x.ip = request.env['REMOTE_ADDR']
    x.username = (cookies["username"] || "").gsub(/[^a-z0-9_\s-]/i, "")[0..20]
    x.save
    ident
  end

  def remove_session(workon)
    return unless workon && params[:ident]
    Session.unscoped.delete_all(
      :cont => workon.class.to_s.pluralize.downcase,
      :viewed_id => workon.id,
      :ident => params[:ident]
    )
  end
end

web/app/helpers/hitmes_helper.rb
# encoding: utf-8

module HitmesHelper
  include FunkyTeXBits

  def text_to_list(text)
    return "" if text.blank?
    "\\begin{compactitem}\n\\item " + text.strip.gsub("\n", "\n\\item ") + "\n\\end{compactitem}"
  end
end

web/app/views/hitmes/_action_buttons.html.erb
<div class="group">
  <span class="button-group">
    <%= submit_tag("Save and give more work", :class => "button primary", :name => "save_and_work", :accesskey => "s", :title => "Saves your changes and advanced to the next step.\nYou will be given a new chunk of work.\nAccessible via Alt+Shift+S or Ctrl+Enter.", :id => "main_submit_button") %>
    <%= submit_tag("Save and quit", :class => "button", :name => "save_and_quit", :title => "Saves your changes and advanced to the next step.\nYou will be returned to the overview page.") %>
    <%= submit_tag("incomplete / can’t read / skip", :class => "button", :name => "save_and_skip", :title => "Saves your changes but does NOT advance to the next step.\nYou will be given a new chunk of work.") %>

    <%# confirmation handled by prevent-leaving-unsaved-form %>
    <%= link_to("quit without saving", hitme_path, :class => "button danger", :title => "Discards your changes.\nYou will be returned to the overview page.") %>
  </span>
</div>
<script>
  $(document).keydown(function(e) {
    if(e.ctrlKey && e.which === 13 && $("#main_submit_button").length === 1 && confirm("Save changes. Give work. Continue?"))
      $("#main_submit_button").click();
  });
</script>

web/app/views/hitmes/_comment_preview.html.erb
<div class="previewbox">
<h3>Preview</h3>
  <span class="rendermsg"></span><br/><br/>
  <div></div>
</div>

web/app/views/hitmes/combine.html.erb
<%
text = ""
isCourse = false
if @workon.is_a?(Course)
  isCourse = true
  many = @workon.course_profs.size > 1
  @workon.course_profs.each do |cp|
    next if cp.c_pics.all? { |p| p.text.blank? }
    text << %(\\vspace{0.4cm}\\textbf{#{cp.prof.fullname}}\n) if many
    text << %(\\begin{compactitem}\n)
    cp.c_pics.map { |p| p.text.split("\n") }.flatten.each do |t|
      next if t.blank?
      text << %(  \\item #{t.strip}\n)
    end
    text << %(\\end{compactitem}\n\n\n)
  end
elsif @workon.is_a?(Tutor)
  unless @workon.pics.all? { |p| p.text.blank? }
    text << %(\\begin{compactitem}\n)
    @workon.pics.map { |p| p.text.split("\n") }.flatten.each do |t|
      next if t.blank?
      text << %(  \\item #{t.strip}\n)
    end
    text << %(\\end{compactitem}\n\n\n)
  end
else
  raise "Unknown class; not implemented"
end
%>

<% content_for :title, " // Combine!" %>
<%= render "shared/aceify_textareas", :line_offset => texpreview_header_offset, :autosize => true %>
<% content_for :script, %(<script>
  var hitme_preview_url="#{hitme_preview_text_url}";
  var ident = '#{@ident}';
  var combinedText = #{text.to_json};

  function setCombinedText() {
    var e = $('#text').data('editor').getSession();

    // only ask if the comment field is not empty
    if($.trim(e.getValue()) !== "" && !confirm('This will overwrite the current text in the comment field. Continue?'))
      return;

    e.setValue(combinedText);
    renderPreview();
  }

    $(document).ready(function() { $('#text').data('editor').focus() });
</script>).html_safe %>
<% content_for :script, javascript_include_tag("hitme_comment_preview") %>


<div class="containersplit">
  <div class="leftside">
    <h2>Your Job: sort / combine</h2>
    <ul>
      <li>Does not look like this?  Click “start over (autocombine comments)“<br/>
        <tt>\begin{compactitem}&nbsp;&nbsp;&nbsp;&nbsp;\item …&nbsp;&nbsp;&nbsp;\end{compactitem}</tt>
      </li>
      <li><b>keep</b> the <b>compactitem</b>-environment, even for one comment</li>
      <li>
        <b>combine repeated comments</b>, i.e. change<br/>
        <tt>&nbsp;&nbsp;\item script would be nice<br/>
          &nbsp;&nbsp;\item (37 comments with the same meaning)
        </tt><br/>
      to<br/>
        <tt>&nbsp;&nbsp;\item a script would be helpful (39$\times$)</tt>
      </li>
      <li><b>Sort:</b> <tt>Microphone, Friendly, M, F</tt> → <tt>M, M, F, F</tt></li>
      <li><b>Group</b> by topic (profs, exercices, study groups, …)</li>
      <li><b>Where do comments belong?</b>
        <ul><li>Concerns tutor or this and only this study group? Tutor</li>
            <li>Concerns anything else? Course</li>
        </ul>
      </li>
      <li>
       <b>Comment doesn’t belong here?</b> Move it to the top:<br/>
       <tt>&nbsp;&nbsp;\item prof rocks! %%%%%% should be moved to prof<br/>
          \begin{compactitem} &nbsp;&nbsp;\item Tutor sucks…</tt>
      </li>
      <li>ensure insults are commented out. Don’t delete them!</li>
      <li><a onclick="alert('\\item tutor Bruno ist Doof is really legendary %%%%% does not belong here, move to tutor “Bruno ist Doof”\n\n\\vspace{0.4cm}\\textbf{Rebecca ist Doof}\n\\begin{compactitem}\n% \\item kill yourself %%% insulting, commented out\n  \\item nice handwriting\n  \\item please write smaller\n  \\item handwriting illegible\n  \\item microphone broken\n\\end{compactitem}\n\n\\vspace{0.4cm}\\textbf{Exercises}\n\\begin{compactitem}\n  \\item exercises are too hard\n  \\item handing out exercices on friday is evil\n  \\item …\n\\end{compactitem}\n\n\\vspace{0.4cm}\\textbf{Study Groups}\n\\begin{compactitem}\n  \\item study groups overlap with courses\n  \\item …\n\\end{compactitem}')">Show a complete example for courses</a>. Tutors usually don’t need grouping.</li>
    </ul><br/>

    <a onclick="setCombinedText()">start over (“auto combine comments”)</a>
  </div>

  <%= render "meta_information", :workon => @workon %>
</div>

<%= form_tag(:controller => "hitmes", :action => "save_combination") %>
  <%= hidden_field_tag(:type, @workon.class) %>
  <%= hidden_field_tag(:id, @workon.id) %>
  <%= hidden_field_tag(:ident, @ident) %>
  <div class="group containersplit">
    <%= render "comment_preview" %>
    <h3>Input</h3>
    <%= text_area_tag(:text, @workon.comment.blank? ? text : @workon.comment)%>
  </div>

  <%= render "action_buttons" %>
</form>

web/app/views/hitmes/final_check.html.erb
<% content_for :title, " // Final Check!" %>
<% content_for :script, "<script>var ident = '#{@ident}'</script>".html_safe %>
<%= render "shared/aceify_textareas", :line_offset => texpreview_header_offset, :autosize => true %>
<% content_for :script, %(<script>var hitme_preview_url="#{hitme_preview_text_url}"</script>).html_safe%>
<% content_for :script, javascript_include_tag("hitme_comment_preview") %>


<div class="containersplit">
  <div class="leftside">
    <h2>Your Job: Final Check!</h2>
    <ul>
      <li><b>move misplaced comments to the correct position.</b><br>Rule of thumb:
      <ul><li>concerns tutor or study group’s room? Put in tutor’s text box.</li><li>everything else? Put in course’s one.</li></ul>
      If your colleagues did good work, you should easily spot those at the top of each text box.</li>
      <li>Check for improper use of quotation marks. Correct ones are <b>„Deutsch“</b> or <b>“English”</b>.</li>
      <li>Otherwise: use your intuition.</li>
    </ul><br/>
  </div>

  <%= render "meta_information", :workon => @workon %>
</div>

<%= form_tag(:controller => "hitmes", :action => "save_final_check") %>
  <%= hidden_field_tag(:id, @workon.id) %>
  <%= hidden_field_tag(:ident, @ident) %>
  <div class="group containersplit">
    <%= render "comment_preview" %>
    <h3>Profs / Course Comment</h3>
    <%= text_area_tag(:course, @workon.summary, :class => "previewable")%>
  </div>

  <% @workon.tutors.each do |tutor| %>
    <div class="group containersplit">
      <%= render "comment_preview" %>
      <h3>Tutor: <%=tutor.abbr_name%></h3>
      <%= text_area_tag("tutor[#{tutor.id}]", tutor.comment, :class => "previewable")%>
    </div>

  <% end %>

  <%= render "action_buttons" %>
</form>

web/app/views/hitmes/overview.html.erb
<% content_for :css, ".broken, .broken * { color: red }" %>
<% content_for :css, ".itworks, .itworks * { color: darkgreen }" %>
<% content_for :css, ".unknown, .unknown * { color: orange }" %>
<% content_for :script, javascript_include_tag("viewer_count") %>
<% content_for :script do %>
<script>
  function setStatus(object, worked) {
    $("#" + object.toLowerCase())
      .attr("class", (worked ? "itworks" : "broken"))
      .html((worked ? "✔" : "✘")+ " <b>"+object+" </b>");
  }

  function updateUsername() {
    if(usernameValid())
      $("#currentUsername").html("(currently known as <b>" + getUsernameCookie() + "</b>)");
    else
      $("#currentUsername").html("(no username set)");
  }

  function giveWork() {
    if($('.broken').size() !== 0) {
      alert("Please fix the issues mentioned above before continuing.");
      return;
    }
    location.href = "<%=hitme_assign_work_url%>";
  }

  function updateActiveUsers() {
    $("#active_users").load("<%=hitme_active_users_path%>", function() {
      setTimeout("updateActiveUsers()", 10000);
    });
  }

  function skipCourse(elm) {
    console.log("running");
    var id = $(elm).val();
    var c = id + "; expires=Thu, 31 Dec 2020 23:59:59 GMT; path=/";
    document.cookie = "skip_course=" + c;
  }

  $(document).ready(function() {
    if(getCookie("testcookie") === "test value" || usernameValid()) {
      setStatus("Cookies", true);
    } else {
      document.cookie = "testcookie=test value; expires=Thu, 31 Dec 2020 23:59:59 GMT; path=/"
      $.getJSON("<%=url_for(:controller => "hitmes", :action => "cookie_test")%>",  function(result) {
        setStatus("Cookies", result);
      });
    }

    updateUsername();
    setStatus("Username", usernameValid());

    // keep active users display up to date
    setTimeout("updateActiveUsers()", 10000);
  });
</script>
<% end %>

<div>
  <h2>What is this?</h2>
  Each Hitme is a <b>small unit of work</b>. It requires <b>no time commitment</b> on your side, so you can even do it in very short breaks. You don’t even need to finish if you’re interrupted.<br><br>
  There are multiple steps:
  <ol>
    <li>type handwritten comment</li>
    <li>proofread</li>
    <li>group/sort comments</li>
    <li>final touches</li>
  </ol><br/>

  The last two steps might take more than five minutes, depending on the lecture. If you don’t have that amount of time right now, you can skip this chunk of work and be assigned another one. Or you could start, but mark it as incomplete and leave it for the next person to finish. Just click the correct button below each hitme.
</div>

<div>
  <h2>What do I need?</h2>

  <span class="noscript broken"><b>✘ JavaScript </b></span> – Ensure JavaScript is enabled for the whole domain and that you don’t block any of its features.<script>$(".noscript").attr("class", "itworks").html("✔ <b>JavaScript </b>");</script><br/>

  <span id="cookies" class="unknown"><b>? Cookies </b></span> – Enable cookies for the domain. Persistent ones are preferred, so you only need to set your username once.<br/>

  <span id="username" class="unknown"><b>? Username </b></span> – Set a descriptive username, so others may easily identify who is working on what.<br/><br/>

  <a onclick="setUsernameCookie(); setStatus('Username', usernameValid()); updateUsername();"><b>Change Username</b></a>
  <span id="currentUsername"></span><br/><br/><br/>
  <a onclick="giveWork();" style="font-size:150%;font-weight:bold">Give me a chunk of work</a><br/><br/><br/>

  <h3>I’m a tutor</h3>
  <%
    c = Term.currently_active.map { |t| t.courses }.flatten
    courses = options_from_collection_for_select(c, "id", "title", cookies[:skip_course])
  %>

  Select the course for which you are tutor. You will not be given chunks of work for that course.

  <%= select_tag "skip_course", courses, :style => "height:auto;width:auto;max-width:20rem;", :onchange => "skipCourse(this)", :include_blank => true %><br/>


</div>

<div id="active_users">
  <%=render "active_users"%>
</div>

<div>
  <h3>Progress</h3>
  It’s assumed amount of work scales linearly with number of comments, so take it with a grain of salt.<br/>
  Expecting a further <b><%=Term.sheets_to_go.first.to_i%> questionnaires</b> to be scanned, which are not included below.
  <%
    stages = [Hitme::TYPING, Hitme::PROOFREADING, Hitme::COMBINING, Hitme::FINALCHECK, Hitme::DONE]
    data = stages.map { |s| Hitme.get_all_comments_by_step(s).size }
    all = data.sum.to_f

    def n(d, all)
      number_to_percentage( 100*d/all, :precision => 0)
    end
  %>
  <table>
    <tr><th>typing          </th><td><%=n(all-data[0]        , all)%></td><td rowspan="4" style="font-size:400%;padding-left:2rem"> Σ=<%=n((data[1] + 2*data[2] + 3*data[3] + 4*data[4])/4.0, all)%></td></tr>
    <tr><th>proofreading    </th><td><%=n(all-data[0]-data[1], all)%></td></tr>
    <tr><th>grouping/sorting</th><td><%=n(data[3]+data[4]    , all)%></td></tr>
    <tr><th>final touching  </th><td><%=n(data[4]            , all)%></td></tr>
  </table>
</div>